name: ESLint
on: push
jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v3
    - name: Install ESLint
      run: |
        npm install eslint@^8.42.0
        npm install eslint-config-airbnb-base@^15.0.0
    - name: Run ESLint
      run: npx eslint .